// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDrH-8PtqjIYBo_X2BfHn-B0KGlBmKA7mk',
//     appId: '1:870316091372:web:e1b5e544879039f24b02c9',
//     messagingSenderId: '870316091372',
//     projectId: 'todo-application-assignm-7378a',
//     authDomain: 'todo-application-assignm-7378a.firebaseapp.com',
//     storageBucket: 'todo-application-assignm-7378a.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAyeckdOIfm6vD_CslV1XfkVZ4Rg3bcnsc',
//     appId: '1:870316091372:android:6a2bcbab70cd683a4b02c9',
//     messagingSenderId: '870316091372',
//     projectId: 'todo-application-assignm-7378a',
//     storageBucket: 'todo-application-assignm-7378a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB9ES7EG_VGTaZe_eTSSKOoSOfWad2gT-w',
//     appId: '1:870316091372:ios:b3b97f0c39591ade4b02c9',
//     messagingSenderId: '870316091372',
//     projectId: 'todo-application-assignm-7378a',
//     storageBucket: 'todo-application-assignm-7378a.appspot.com',
//     iosBundleId: 'com.example.todoappassi5',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDrH-8PtqjIYBo_X2BfHn-B0KGlBmKA7mk',
//     appId: '1:870316091372:web:7f38335a94c351944b02c9',
//     messagingSenderId: '870316091372',
//     projectId: 'todo-application-assignm-7378a',
//     authDomain: 'todo-application-assignm-7378a.firebaseapp.com',
//     storageBucket: 'todo-application-assignm-7378a.appspot.com',
//   );
// }
